[[pages]]
name = "Home"
icon = "ğŸ "
is_section = true

[[pages]]
path = "pages/1_ğŸ¤–_text_to_sql_client.py"
name = "Insight to Data"
icon = "ğŸ¤–"


[[pages]]
path = "pages/2_ğŸ“ˆ_text_to_sql_metrics.py"
name = "Metrics"
icon = "ğŸ“ˆ"