[[pages]]
name = "Document Explorer"
icon = "ğŸ“"
is_section = true

[[pages]]
path = "pages/1_doc_explorer_home.py"
name = "Home"
icon = "ğŸ "


[[pages]]
path = "pages/2_Select_Document.py"
name = "Select Document"
icon = "ğŸ“ƒ"

[[pages]]
path = "pages/3_Q&A.py"
name = "Q&A"
icon = "ğŸ’¬"

[[pages]]
path = "pages/4_Summary.py"
name = "Summary"
icon = "ğŸ·ï¸"

[[pages]]
path = "pages/5_Visual_Q&A.py"
name = "Visual Q&A"
icon = "ğŸ‘ï¸â€ğŸ—¨ï¸"