[[pages]]
name = "Home"
icon = "ğŸ "
is_section = true

[[pages]]
path = "pages/1_content_generation_home.py"
name = "Home"
icon = "ğŸ "


[[pages]]
path = "pages/2_Image_Generation.py"
name = "Generate Image"
icon = "ğŸ“¸"