[[pages]]
name = "Home"
icon = "ğŸ "
is_section = true

[[pages]]
path = "pages/1_image_generation_home.py"
name = "Home"
icon = "ğŸ "


[[pages]]
path = "pages/2_image_description.py"
name = "Generate Image Descriptions"
icon = "ğŸ“¸"